[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/python -m ensurepip --upgrade",
  "/opt/venv/bin/python -m pip install -r requirements-deploy.txt",
]

[start]
cmd = "/opt/venv/bin/python my_bot.py"
